import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { buildSkillMdTemplate } from "./templates.js";

const MANAGED_HEADER = "<!-- AUTO-GENERATED BY SDD. DO NOT EDIT MANUALLY. -->\n";

export type AdapterMode = "pointer" | "mirror";

export interface SkillAdapterDefinition {
  id: string;
  mode: AdapterMode;
  paths: string[];
}

export interface SyncAdaptersOptions {
  agents?: string[];
  force?: boolean;
  dryRun?: boolean;
  experimentalAllowedTools?: boolean;
}

export type AdapterFileAction = "created" | "updated" | "skipped";

export interface AdapterFileChange {
  path: string;
  action: AdapterFileAction;
  reason?: string;
}

export interface SyncAdaptersResult {
  canonical: AdapterFileChange[];
  adapters: AdapterFileChange[];
  selectedAgents: string[];
}

const CANONICAL_BASE_DIR = ".sdd/skill/sdd";

function getCanonicalFiles(options?: SyncAdaptersOptions): Array<{ path: string; content: string }> {
  return [
    {
      path: `${CANONICAL_BASE_DIR}/SKILL.md`,
      content: buildSkillMdTemplate({ experimentalAllowedTools: options?.experimentalAllowedTools }),
    },
  ];
}

export const SKILL_ADAPTERS: SkillAdapterDefinition[] = [
  {
    id: "claude",
    mode: "mirror",
    paths: [".claude/skills/sdd/SKILL.md"],
  },
  {
    id: "copilot",
    mode: "pointer",
    paths: [".github/copilot-instructions.md"],
  },
  {
    id: "cursor",
    mode: "pointer",
    paths: [".cursor/rules/sdd.mdc"],
  },
  {
    id: "gemini",
    mode: "pointer",
    paths: ["GEMINI.md"],
  },
  {
    id: "jetbrains",
    mode: "pointer",
    paths: [".junie/guidelines.md"],
  },
  {
    id: "grok",
    mode: "pointer",
    paths: ["GROK.md"],
  },
  {
    id: "opencode",
    mode: "pointer",
    paths: ["OPENCODE.md"],
  },
  {
    id: "universal",
    mode: "pointer",
    paths: ["AGENTS.md"],
  },
];

export function listSupportedAdapters(): string[] {
  return SKILL_ADAPTERS.map((adapter) => adapter.id);
}

export async function syncSkillAdapters(root: string, options?: SyncAdaptersOptions): Promise<SyncAdaptersResult> {
  const force = options?.force ?? false;
  const dryRun = options?.dryRun ?? false;
  const selected = resolveSelectedAdapters(options?.agents);
  const canonicalFiles = getCanonicalFiles(options);

  const canonicalChanges: AdapterFileChange[] = [];
  for (const file of canonicalFiles) {
    const change = await upsertFile(root, file.path, file.content, {
      force,
      dryRun,
      managed: false,
    });
    canonicalChanges.push(change);
  }

  const adapterChanges: AdapterFileChange[] = [];
  for (const adapter of selected) {
    if (adapter.mode === "pointer") {
      const content = buildPointerContent(adapter.id);
      for (const path of adapter.paths) {
        const change = await upsertFile(root, path, content, {
          force,
          dryRun,
          managed: true,
        });
        adapterChanges.push(change);
      }
      continue;
    }

    for (let i = 0; i < adapter.paths.length; i += 1) {
      const canonical = canonicalFiles[i];
      if (!canonical) {
        adapterChanges.push({ path: adapter.paths[i], action: "skipped", reason: "No canonical source file" });
        continue;
      }

      const change = await upsertFile(root, adapter.paths[i], canonical.content, {
        force,
        dryRun,
        managed: false,
      });
      adapterChanges.push(change);
    }
  }

  return {
    canonical: canonicalChanges,
    adapters: adapterChanges,
    selectedAgents: selected.map((adapter) => adapter.id),
  };
}

function resolveSelectedAdapters(agents?: string[]): SkillAdapterDefinition[] {
  if (!agents || agents.length === 0) {
    return SKILL_ADAPTERS;
  }

  const normalized = new Set(agents.map((agent) => agent.trim().toLowerCase()).filter(Boolean));
  const selected = SKILL_ADAPTERS.filter((adapter) => normalized.has(adapter.id));

  const missing = Array.from(normalized).filter((agent) => !SKILL_ADAPTERS.some((adapter) => adapter.id === agent));

  if (missing.length > 0) {
    throw new Error(`Unsupported adapters: ${missing.join(", ")}`);
  }

  return selected;
}

function buildPointerContent(adapterId: string): string {
  if (adapterId === "cursor") {
    return `---
description: SDD workflow adapter
alwaysApply: false
---

Read .sdd/skill/sdd/SKILL.md for the full SDD workflow.
`;
  }

  return `# SDD Adapter (${adapterId})

Primary instructions: .sdd/skill/sdd/SKILL.md

Fallback (legacy): .claude/skills/sdd/SKILL.md
`;
}

async function upsertFile(
  root: string,
  relativePath: string,
  content: string,
  options: { force: boolean; dryRun: boolean; managed: boolean },
): Promise<AdapterFileChange> {
  const absPath = resolve(root, relativePath);
  const finalContent = options.managed ? `${MANAGED_HEADER}${content}` : content;

  if (!existsSync(absPath)) {
    if (!options.dryRun) {
      await mkdir(dirname(absPath), { recursive: true });
      await writeFile(absPath, finalContent, "utf-8");
    }
    return { path: relativePath, action: "created" };
  }

  const current = await readFile(absPath, "utf-8");
  if (current === finalContent) {
    return { path: relativePath, action: "skipped", reason: "Already up to date" };
  }

  if (!options.force) {
    return { path: relativePath, action: "skipped", reason: "Exists (use --force to overwrite)" };
  }

  if (!options.dryRun) {
    await writeFile(absPath, finalContent, "utf-8");
  }
  return { path: relativePath, action: "updated" };
}
